# Generated by Django 2.2.13 on 2020-07-16 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategyreply',
            name='send_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='发送时间'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='strategycomment',
            name='good',
            field=models.IntegerField(default=0, verbose_name='赞'),
        ),
        migrations.AlterField(
            model_name='strategyreply',
            name='touser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='strategycomment_to', to='user.User'),
        ),
    ]
