# Generated by Django 2.2.13 on 2020-07-21 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0002_auto_20200716_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='introduce',
            field=models.TextField(default=' '),
        ),
    ]
