# Generated by Django 2.2.13 on 2020-07-22 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='cover_img',
            field=models.ImageField(default=None, upload_to='hotel'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='scenic',
            field=models.ManyToManyField(default=None, to='scenic.Scenic'),
        ),
    ]
