# Generated by Django 2.2.13 on 2020-07-23 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_auto_20200723_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='area',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='scenic.Area'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='city',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='scenic.City'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='province',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='scenic.Province'),
        ),
    ]
