# Generated by Django 2.2.13 on 2020-07-23 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_auto_20200723_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='area',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='city',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='province',
        ),
    ]
